
{{- range $export := .Values.exports }}
  {{- range $i := (untilStep 0 (int .count) 1) }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ $export.name }}-{{ printf "%03d" (add1 $i) }}
spec:
  capacity:
    storage: {{ $export.size }}
  accessModes:
  - ReadWriteOnce
  nfs:
    path: {{ $.Values.exports_path }}/{{ $export.name }}_{{ printf "%03d" (add1 $i) }}
    server: {{ $.Values.server }}
  persistentVolumeReclaimPolicy: Retain
  {{- end }}
{{- end }}